sudo: required
services:
  - docker

before_install:
  - docker build -t onechaiev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true onechaiev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-850109877226"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
